services:
    postgres:
        build: postgres
        image: kjelstromjr/csc468-postgres:latest
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: database
        volumes:
            - postgres_data:/var/lib/postgresql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d database"]
            interval: 5s
            timeout: 5s
            retries: 5

    node:
        build: node
        image: kjelstromjr/csc468-node:latest
        container_name: node
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        command: node app.js

volumes:
    postgres_data: